### PR TITLE
memcached: fix upper value for readahead parameter

### LINKED ISSUE #103: Wrong check for 'readahead' option value
```lua
tarantool> mc = require('memcached')
tarantool> m.opts.readahead
---
- 16320
...

tarantool> m:cfg({readahead = 16320})
---
- error: '/home/sergeyb/sources/MRG/memcached/memcached/init.lua:270: Bad value for
    argument ''readahead'''
...

tarantool> 
```

### PR DESCRIPTION
**Pull request by ligurio**
Fix #103

### CODE REVIEW

File: memcached/init.lua [hunk 1]
```diff
@@ -109,7 +109,7 @@ local typetable = {
     readahead = {
         'number',
         function() return box.cfg.readahead end,
-        function(x) return x > 0 and x < math.pow(2, 10) end,
+        function(x) return x > 0 and x <= box.cfg.readahead end,
```
Comment (Totktonada) [inline memcached/init.lua:112]: I don't see a reason, why this buffer should be bounded by current iproto buffer size. They're independent.

However we can steal the maximum from its [validation code](https://github.com/tarantool/tarantool/blob/297c33492f8697350f78754fe3cb166f700c16ae/src/box/box.cc#L1091-L1100). It is `math.pow(2, 31) - 1`.

**Review by Totktonada — APPROVED** [review]
LGTM.
