### PR TITLE
memcached: check tarantool's box before init

### LINKED ISSUE #76: Unclear error when memcached instance created without box initialization
```lua
sergeyb@pony:~/sources/MRG/memcached$ /home/sergeyb/sources/MRG/tarantool/build/src/tarantool 
Tarantool 2.10.0-beta1-257-g14aa6a597
type 'help' for interactive help
tarantool> mc = require('memcached')
---
...

tarantool> mc.create('instance', '127.0.0.1:8080', { proto = 'text'})
---
- error: '/home/sergeyb/sources/MRG/memcached/memcached/init.lua:111: attempt to index
    field ''cfg'' (a function value)'
...

tarantool> 
```

memcached/init.lua:
```lua
109     readahead = {                                                                
110         'number',                                                                
111         function() return box.cfg.readahead end,                                 
112         function(x) return x > 0 and x < math.pow(2, 10) end,                    
113         [[size of readahead buffer]]                                             
114     },                                                                           
115     expire_enabled = {                                                           
116         'boolean',                                               
```

Version: 617478d945d95dedcb517b6063d258a68a6ebfad

### PR DESCRIPTION
**Pull request by ligurio**
memcached shows unclear error when memcached instance created without box
initialization:

```
tarantool> mc = require('memcached')
tarantool> mc.create('instance', '127.0.0.1:8080', { proto = 'text'})
---
- error: '/home/sergeyb/sources/MRG/memcached/memcached/init.lua:111: attempt to index
    field ''cfg'' (a function value)'
...
```

With patch memcached checks whether box is initialized or not and shows a
correct message:
```
tarantool> mc.create('instance', '127.0.0.1:8080', { proto = 'text'})
---
- error: '/home/sergeyb/sources/MRG/memcached/memcached/init.lua:344: Tarantool must
    be initialized with box.cfg()'
...
```
Fixes #76

### CODE REVIEW

File: memcached/init.lua [hunk 1]
```diff
@@ -185,6 +185,7 @@ local typetable = {
 }
 
 local err_enomem          = "Can't allocate memory for %s"
+local err_bad_box         = "Tarantool must be initialized with box.cfg()"
```
Comment (Totktonada) [inline memcached/init.lua:188]: A terminological nitpicking: tarantool is an application server and a database. `box.cfg()` initializes the dababase part, while the whole application server can work without this.

I would reflect Tarantool's message here:

```lua
tarantool> (select(2, pcall(function() return box.info end)):gsub('^[^ ]+ ([^\n]+).*$', '%1'))
---
- Please call box.cfg{} first
...
```

**Review by Totktonada — APPROVED** [review]
Thanks! LGTM.

File: memcached/init.lua (hunk 1 above)
Comment (ligurio) [reply memcached/init.lua:188]: Thanks for suggestion!

I updated a patch:
```lua
--- a/memcached/init.lua
+++ b/memcached/init.lua        
@@ -185,7 +185,6 @@ local typetable = {
 }            
              
 local err_enomem          = "Can't allocate memory for %s"
-local err_bad_box         = "Tarantool must be initialized with box.cfg()"
 local err_bad_args        = "Arguments must be in dictionary"
 local err_no_such_option  = "No such option '%s'"
 local err_bad_option_type = "Bad '%s' option type, expected '%s', got '%s'"
(1/2) Stage this hunk [y,n,q,a,d,j,J,g,/,e,?]? y                                                                                        
@@ -340,8 +339,9 @@ local function memcached_init(name, uri, opts)
         end                    
         return memcached_services[name]  
     end
-    if type(box.cfg) == 'function' then
-        error(fmt(err_bad_box, name))
+    local _, err = pcall(function() return box.info end)
+    if err ~= nil then
+        error(err:gsub('^[^ ]+ ([^\n]+).*$', '%1'))
     end
     local conf = config_initial(opts)
     local instance = {}
```

Please you advice: can I rely on regexp or may be better to show my own error message?

Comment (ligurio) [reply memcached/init.lua]: changed:

```lua
--- a/memcached/init.lua
+++ b/memcached/init.lua
@@ -186,6 +186,7 @@ local typetable = {
 
 local err_enomem          = "Can't allocate memory for %s"
 local err_bad_args        = "Arguments must be in dictionary"
+local err_bad_box         = "Please call box.cfg{} first"
 local err_no_such_option  = "No such option '%s'"
 local err_bad_option_type = "Bad '%s' option type, expected '%s', got '%s'"
 local err_bad_value       = "Bad value for argument '%s'"
@@ -339,6 +340,9 @@ local function memcached_init(name, uri, opts)
         end
         return memcached_services[name]
     end
+    if type(box.cfg) == 'function' then
+        error(fmt(err_bad_box, name))
+    end
     local conf = config_initial(opts)
     local instance = {}
     instance.opts = conf
```

Comment (Totktonada) [reply memcached/init.lua]: Thanks!
