### PR TITLE
memcached: use own small's arena

### LINKED ISSUE #96: All memcached tests fail with tarantool 2.10.0-beta1-376-gd2a012455 (master branch)
Host: `Ubuntu 20.04`

Tarantool:
```
Tarantool 2.10.0-beta1-376-gd2a012455
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.376.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.376.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

Try to run tests:
```bash
$ make test-memcached
[  3%] Built target generate_proto_txt_parser_c
[ 11%] Built target msgpuck
[ 55%] Built target small
[100%] Built target internalso
Scanning dependencies of target test-memcached
Started ./test-run.py --force
Collecting tests in 'binary': memcached binary tests.
Found 4 tests.
Collecting tests in 'capable': memcapable integration.
Found 2 tests.
Collecting tests in 'sasl': memcached binary sasl tests.
Found 1 tests.
Collecting tests in 'text': memcached text tests.
Found 10 tests.
Installing the server ...
    Found executable at /usr/bin/tarantool
    Found tarantoolctl at  /usr/bin/tarantoolctl
    Creating and populating working directory in /home/ubuntu/Workspace/memcached/test/var ...
    Found old vardir, deleting ...
Starting the server ...
Starting /home/ubuntu/Workspace/memcached/test/var/binary.lua
Tarantool 2.10.0-beta1-369-g2f55b4168
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.369.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.369.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
================================================================================
TEST                                            PARAMS		RESULT
---------------------------------------------------------------------------
binary/binary-boundary.test.py                                  [ disabled ]
binary/binary-expire.test.py                                    Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "binary/binary-expire.test.py", line 40, in <module>
    server.admin("box.space.__mc_memcached:truncate()", silent=True)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/admin_connection.py", line 88, in connect
    super(AdminConnection, self).connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:
#-----------------------------# test expiration #-----------------------------#

Last 15 lines of Tarantool Log file:
binary/binary-toobig.test.py                                    Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "binary/binary-toobig.test.py", line 12, in <module>
    mc = MemcachedBinaryConnection("127.0.0.1", iproto.py_con.port)
  File "/home/ubuntu/Workspace/memcached/test/binary/internal/memcached_connection.py", line 165, in __init__
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:

Last 15 lines of Tarantool Log file:
binary/binary.test.py                                           Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "binary/binary.test.py", line 12, in <module>
    mc = MemcachedBinaryConnection("127.0.0.1", iproto.py_con.port)
  File "/home/ubuntu/Workspace/memcached/test/binary/internal/memcached_connection.py", line 165, in __init__
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:

Last 15 lines of Tarantool Log file:
---------------------------------------------------------------------------
Stopping the server ...
Failed 3 tests: binary/binary-expire.test.py, binary/binary-toobig.test.py, binary/binary.test.py.
Installing the server ...
    Found executable at /usr/bin/tarantool
    Found tarantoolctl at  /usr/bin/tarantoolctl
    Creating and populating working directory in /home/ubuntu/Workspace/memcached/test/var ...
    Found old vardir, deleting ...
Starting the server ...
Starting /home/ubuntu/Workspace/memcached/test/var/capable.lua
Tarantool 2.10.0-beta1-369-g2f55b4168
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.369.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.369.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
================================================================================
TEST                                            PARAMS		RESULT
---------------------------------------------------------------------------
capable/capable-binary.test.py                                  [ skip ]
capable/capable-text.test.py                                    [ skip ]
---------------------------------------------------------------------------
Stopping the server ...
Installing the server ...
    Found executable at /usr/bin/tarantool
    Found tarantoolctl at  /usr/bin/tarantoolctl
    Creating and populating working directory in /home/ubuntu/Workspace/memcached/test/var ...
    Found old vardir, deleting ...
Starting the server ...
Starting /home/ubuntu/Workspace/memcached/test/var/sasl.lua
Tarantool 2.10.0-beta1-369-g2f55b4168
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.369.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.369.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
================================================================================
TEST                                            PARAMS		RESULT
---------------------------------------------------------------------------
sasl/binary-sasl.test.py                                        [ disabled ]
---------------------------------------------------------------------------
Stopping the server ...
Installing the server ...
    Found executable at /usr/bin/tarantool
    Found tarantoolctl at  /usr/bin/tarantoolctl
    Creating and populating working directory in /home/ubuntu/Workspace/memcached/test/var ...
    Found old vardir, deleting ...
Starting the server ...
Starting /home/ubuntu/Workspace/memcached/test/var/text.lua
Tarantool 2.10.0-beta1-369-g2f55b4168
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.369.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1.369.dev=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
================================================================================
TEST                                            PARAMS		RESULT
---------------------------------------------------------------------------
text/binary-get.test.py                                         Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/binary-get.test.py", line 22, in <module>
    mc_client("set %s 0 0 %d\r\n%s\r\n" % (key, blob_len, blob))
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 143, in execute
    return self.execute_no_reconnect(command, silent)
  File "/home/ubuntu/Workspace/memcached/test/binary/internal/memcached_connection.py", line 558, in execute_no_reconnect
    return self.recv(silent)
  File "/home/ubuntu/Workspace/memcached/test/binary/internal/memcached_connection.py", line 581, in recv
    self.reply_storage(cmd)
  File "/home/ubuntu/Workspace/memcached/test/binary/internal/memcached_connection.py", line 606, in reply_storage
    self.reply_single_line(cmd)
  File "/home/ubuntu/Workspace/memcached/test/binary/internal/memcached_connection.py", line 686, in reply_single_line
    reply = self.read_line() + MEMCACHED_SEPARATOR
  File "/home/ubuntu/Workspace/memcached/test/binary/internal/memcached_connection.py", line 702, in read_line
    data = self.socket.recv(1048576)
error: [Errno 104] Connection reset by peer
[ fail ]
Test failed! Last 10 lines of the result file:
<<--------------------------------------------------
set foo_0 0 0 5
mooo

Last 15 lines of Tarantool Log file:
text/bogus-commands.test.py                                     Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/bogus-commands.test.py", line 15, in <module>
    mc_client("boguscommand slkdsldkfjsd\r\n")
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:

Last 15 lines of Tarantool Log file:
text/cas.test.py                                                Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/cas.test.py", line 15, in <module>
    mc_client("cas bad blah 0 0 0\r\n")
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:

Last 15 lines of Tarantool Log file:
text/expirations.test.py                                        Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/expirations.test.py", line 15, in <module>
    master_id = server.get_param('server')['id']
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 807, in get_param
    return yaml.load(self.admin("box.info." + param, silent=True))[0]
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/admin_connection.py", line 88, in connect
    super(AdminConnection, self).connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:

Last 15 lines of Tarantool Log file:
text/flags.test.py                                              Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/flags.test.py", line 18, in <module>
    mc_client("set foo %d 0 6\r\nfooval\r\n" % flags)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:

Last 15 lines of Tarantool Log file:
text/flush-all.test.py                                          Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/flush-all.test.py", line 30, in <module>
    mc_client("set foo 0 0 6\r\nfooval\r\n")
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:
# Test flush_all with zero delay.

Last 15 lines of Tarantool Log file:
text/getset.test.py                                             Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/getset.test.py", line 15, in <module>
    mc_client("flush_all\r\n", silent = True)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:

Last 15 lines of Tarantool Log file:
text/incrdecr.test.py                                           Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/incrdecr.test.py", line 16, in <module>
    mc_client("set bug21 0 0 19\r\n9223372036854775807\r\n")
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:
# incr/decr big value

Last 15 lines of Tarantool Log file:
text/multiversioning.test.py                                    Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/multiversioning.test.py", line 24, in <module>
    print memcached1("set big 0 0 %d\r\n%s\r\n" % (buf_size, buf), silent = True)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:
# Store big in lower case via first memcached client
set big 0 0 262144
<big-value-lower-case>

Last 15 lines of Tarantool Log file:
text/noreply.test.py                                            Traceback (most recent call last):
  File "/home/ubuntu/Workspace/memcached/test-run/lib/test.py", line 135, in run
    self.execute(server)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_server.py", line 137, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "text/noreply.test.py", line 16, in <module>
    mc_client("flush_all noreply\r\n")
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 153, in __call__
    return self.execute(command, silent)
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 142, in execute
    self.opt_reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 136, in opt_reconnect
    self.reconnect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 121, in reconnect
    self.connect()
  File "/home/ubuntu/Workspace/memcached/test-run/lib/tarantool_connection.py", line 110, in connect
    self.socket = socket.create_connection((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[ fail ]
Test failed! Last 10 lines of the result file:
# Test that commands can take 'noreply' parameter.

Last 15 lines of Tarantool Log file:
---------------------------------------------------------------------------
Stopping the server ...
Failed 10 tests: text/binary-get.test.py, text/bogus-commands.test.py, text/cas.test.py, text/expirations.test.py, text/flags.test.py, text/flush-all.test.py, text/getset.test.py, text/incrdecr.test.py, text/multiversioning.test.py, text/noreply.test.py.

===== 13 tests failed:
----- binary/binary-expire.test.py
----- binary/binary-toobig.test.py
----- binary/binary.test.py
----- text/binary-get.test.py
----- text/bogus-commands.test.py
----- text/cas.test.py
----- text/expirations.test.py
----- text/flags.test.py
----- text/flush-all.test.py
----- text/getset.test.py
----- text/incrdecr.test.py
----- text/multiversioning.test.py
----- text/noreply.test.py
[INFO/MainProcess] process shutting down
make[3]: *** [test/CMakeFiles/test-memcached.dir/build.make:57: test/CMakeFiles/test-memcached] Error 255
make[2]: *** [CMakeFiles/Makefile2:1067: test/CMakeFiles/test-memcached.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1074: test/CMakeFiles/test-memcached.dir/rule] Error 2
make: *** [Makefile:580: test-memcached] Error 2
```

However, tests work fine with `tarantool 2.8.2-80-g69fc3de62`.

### PR DESCRIPTION
**Pull request by ligurio**
Fixes #96

### CODE REVIEW

File: memcached/internal/memcached.c [hunk 1]
```diff
@@ -51,6 +51,20 @@
...
+{
+	slab_info.arena_size = arena.used;
+
+	slab_info.quota_used = quota_used(arena.quota);
+	slab_info.quota_size = quota_total(arena.quota);
+	slab_info.quota_used_ratio = 100 * ((double) slab_info.quota_used /
+					((double) slab_info.quota_size + 0.0001));
+
+	return &slab_info;
+}
```
Comment (Totktonada) [inline memcached/internal/memcached.c:67]: `arena_used` and `arena_used_ratio` are not filled here. And, it seems, they are never filled and always zero in current implementation.

File: memcached/init.lua [hunk 2]
```diff
@@ -386,7 +410,20 @@ local function memcached_get(name)
     return memcached_services[name]
 end
 
+local function memcached_slab()
+    local slab_arena_info = memcached_internal.memcached_slab_arena_info()
+    local slab = {
+        info = {}
+    }
+    for _, v in pairs(slab_arena_info_table) do
+	slab.info[v] = slab_arena_info[0][v]
```
Comment (Totktonada) [inline memcached/init.lua:419]: It seems, a tab symbol is here (or indent is wrong due to some other reason).

**Review by Totktonada — COMMENTED** [review]
While I'm thinking on the patchset and collecting review comments to discuss, I'll left several trivial comments, which are easy to fix.

File: .github/workflows/testing.yaml [hunk 3]
```diff
@@ -23,11 +23,18 @@ jobs:
...
+        if: matrix.tarantool-version != '2.10'
         uses: tarantool/setup-tarantool@v1
         with:
           tarantool-version: ${{ matrix.tarantool-version }}
 
+      - name: Setup Tarantool (2.10)
+        if: matrix.tarantool-version == '2.10'
+        run: |
+          curl -L https://tarantool.io/tWsLBdI/pre-release/2/installer.sh | bash
+          sudo apt install -y tarantool tarantool-dev
```
[the remark this answers is not in the document]
Comment (ligurio) [reply .github/workflows/testing.yaml:36]: 1. removed
2. Github Documentation says that on Github-hosted runners "The Linux and macOS virtual machines both run using passwordless sudo." ([source](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#administrative-privileges-of-github-hosted-runners)), so I removed sudo for line with curl and below with apt.

File: memcached/init.lua (hunk 2 above)
Comment (ligurio) [reply memcached/init.lua:419]: Fixed.

```lua
--- a/memcached/init.lua
+++ b/memcached/init.lua
@@ -416,7 +416,7 @@ local function memcached_slab()
         info = {}
     }
     for _, v in pairs(slab_arena_info_table) do
-       slab.info[v] = slab_arena_info[0][v]
+        slab.info[v] = slab_arena_info[0][v]
     end
 
     return slab
```

File: test/common/instance_api.test.lua [hunk 4]
```diff
@@ -121,3 +121,19 @@ local self_instance = mc:grant('Vera')
 test:isnt(self_instance, nil, 'instance:grant() returns self object')
 
 os.exit(test:check() and 0 or 1)
+
+-- instance:slab()
+
```
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua:126]: > It goes after `os.exit()`. 

Ah, overlooked it. Thanks!

> The test attempts to use `slab()` as an instance method.

It is actually a module function. Fixed commit message and moved testcases from `test/common/instance_api.test.lua`to  `test/common/module_api.test.lua`.

File: memcached/internal/memcached.c (hunk 1 above)
Comment (ligurio) [reply memcached/internal/memcached.c:67]: Yes, it is so. I mentioned it in commit message:

>    With our own slab arena we need a way to obtain information about arena.
>    It's a reason why new module function slab() was introduced. Output of
>    slab() is similar to output from `box.slab.info()`, but without
>    items_size, items_used, items_used_ratio and arena_used is not
>    implemented.

The initial idea was to make the same info as in `box.slab.info()`, but then I decided to don't implement `arena_used` because don't know how to track its usage.

Comment (Totktonada) [reply memcached/internal/memcached.c:67]: So we should not report zeros here.

Comment (ligurio) [reply memcached/internal/memcached.c:67]: ok, I'll remove not implemented counters.

Comment (ligurio) [reply memcached/internal/memcached.c]: removed

File: test/common/instance_api.test.lua [hunk 5]
```diff
@@ -121,3 +121,19 @@ local self_instance = mc:grant('Vera')
...
+test:istable(slab, 'instance:slab() returns a table')
+test:istable(slab.info, 'instance:slab().info returns a table')
+test:isnumber(slab.info.arena_size, 'instance:slab().info.arena_size returns a number')
+test:isnumber(slab.info.arena_used, 'instance:slab().info.arena_used returns a number')
+test:isnumber(slab.info.arena_used_ratio, 'instance:slab().info.arena_used_ratio returns a number')
+test:isnumber(slab.info.quota_size, 'instance:slab().info.quota_size returns a number')
+test:isnumber(slab.info.quota_used, 'instance:slab().info.quota_used returns a number')
+test:isnumber(slab.info.quota_used_ratio, 'instance:slab().info.quota_used_ratio returns a number')
+local quota_used_ratio = 100 * slab.info.quota_used / slab.info.quota_used
+test:is(slab.info.quota_used_ratio, quota_used_ratio, 'instance:slab().info.quota_used_ratio is correct')
```
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua]: Done (without luatest's code).

**Comment by Totktonada** [comment]
Brief feedback:

1. I can't find a reason to spawn slab cache per fiber. In tarantool we have one per cord (IOW, one per thread). Let's initialize it at the module initialization.
2. I would like to see allocator (de)initialization code in `memcached/internal/alloc.c`. I guess three new functions: initialization, deinitialization, get slab cache pointer.
3. Since we have only one arena limited by given quota, we'll always have quota_used == arena_size. If we'll keep just quota stats, it'll looks easier to understand. I would also make `memcached.slab` a table of functions just like `box.slab`, because this way we can add `memcached.info.stats()` later. So I would like to see the following:

   ```lua
   tarantool> memcached.slab.info()
   ---
   - quota_size: <...>
     quota_used: <...>
     quota_used_ratio: <...>%
   ...
   ```

   Here we don't track internal fragmentation (within slabs), but it is enough now.

**Comment by Totktonada** [comment]
Brief feedback:

1. I can't find a reason to spawn slab cache per fiber. In tarantool we have one per cord (IOW, one per thread). Let's initialize it at the module initialization.
2. I would like to see allocator (de)initialization code in `memcached/internal/alloc.c`. I guess three new functions: initialization, deinitialization, get slab cache pointer.
3. Since we have only one arena limited by given quota, we'll always have quota_used == arena_size. If we'll keep just quota stats, it'll looks easier to understand. I would also make `memcached.slab` a table of functions just like `box.slab`, because this way we can add `memcached.info.stats()` later. So I would like to see the following:

   ```lua
   tarantool> memcached.slab.info()
   ---
   - quota_size: <...>
     quota_used: <...>
     quota_used_ratio: <...>%
   ...
   ```

   Here we don't track internal fragmentation (within slabs), but it is enough now.

File: README.md [hunk 6]
```diff
@@ -83,6 +83,7 @@ END
   - `name` - a string with instance name
   - `uri`  - a string with uri to bind to, for example: `0.0.0.0:11211` (only TCP is supported now)
   - `opts` - a table with options, the list of possible options is described in the configuration section
+* `local slab = memcached.slab()` - show information about slab arena and quota.
```
Comment (Totktonada) [inline README.md:86]: Nit: I would place it before `memcached.create()`, which starts a description of things related to an instance.

**Comment by ligurio** [comment]
> I can't find a reason to spawn slab cache per fiber. In tarantool we have one per cord (IOW, one per thread). Let's initialize it at the module initialization.

Done.

> I would like to see allocator (de)initialization code in memcached/internal/alloc.c. I guess three new functions: initialization, deinitialization, get slab cache pointer.

Moved functions for allocations to alloc.c. There is no deinitialization function in memcached and I have no idea how to call it if it would exist, so currently memcached creates arena and shared slab cache and never destroy them.
"get slab cache pointer." - done.

> Since we have only one arena limited by given quota, we'll always have quota_used == arena_size. If we'll keep just quota stats, it'll looks easier to understand. I would also make memcached.slab a table of functions just like box.slab, because this way we can add memcached.info.stats() later. So I would like to see the following:
> 
> tarantool> memcached.slab.info()
> ---
> - quota_size: <...>
>  quota_used: <...>
>  quota_used_ratio: <...>%
> ...
>
> Here we don't track internal fragmentation (within slabs), but it is enough now.

Done.

**Comment by ligurio** [comment]
Tarantool has versions where symbols were opened. I found commits where symbols have been opened (03790a) and commit (5ceabb) where symbols have been closed back. Between two of these commits there were 6 commits where small submodule has been updated. I build Tarantool binary on each commit and run tests against Tarantool binary. All memcached tests were passed successfully.

- Jul 26 2021 [5ceabb](https://github.com/tarantool/tarantool/commit/5ceabb378d0169dc776449e45577515114e39f12) cmake: hide tarantool symbols back
- Jun 4 2021 [8f97c0](https://github.com/tarantool/tarantool/commit/8f97c051279bca424694b429929827551e29c26e) memtx: implement unified interface for getting allocator statistics
- Mar 25 2021 [2dd126](https://github.com/tarantool/tarantool/commit/2dd126fbc479a4782516ded45bf89b8bcf536cda) memtx: move delayed tuples deletion from small allocator to memtx
- Jan 27 2021 [fcfa6b](https://github.com/tarantool/tarantool/commit/fcfa6bcf3c82f742f3ce2ed2db388b4317f60824) memtx: fix memory allocation errors for distributed size tuples
- Jun 16 2021 [ec45e4](https://github.com/tarantool/tarantool/commit/ec45e4cf5847fcea940207c8f5c4f67b36812bb6) small: bump new version (actually c5ae543f329aca07ba12c64ee462f5763ef5c194)
- Mar 16 2021 [9e72c4](https://github.com/tarantool/tarantool/commit/9e72c48a036a704be09882c9c29a7df5c072701f) small: fix flaky test in small
- Jan 14 2021 [53c0e9](https://github.com/tarantool/tarantool/commit/53c0e910aaa49b5242c1144a9229fccc85f45965) memxt: add granularity option to box.cfg{}
- Apr 11 2020 [03790a](https://github.com/tarantool/tarantool/commit/03790ac5510648d1d9648bb2281857a7992d0593) cmake: remove dynamic-list linker option

File: memcached/init.lua [hunk 7]
```diff
@@ -390,6 +405,17 @@ local function memcached_get(name)
     return memcached_services[name]
 end
 
+local function memcached_slab_info()
+    local slab_arena_info = memcached_internal.memcached_slab_arena_info()
+    local slab_info = {}
+    for _, v in pairs(slab_arena_info_table) do
+        slab_info[v] = tonumber(slab_arena_info[0][v])
```
Comment (Totktonada) [inline memcached/init.lua:412]: It is better to use `luaL_pushuint64()` for 64 bit numbers to don't loss precision on large values. The function is in the module API.

```lua
tarantool> tonumber(1152921504606846977ULL)
---
- 1152921504606846976
...
```

File: memcached/internal/alloc.c [hunk 8]
```diff
@@ -1,2 +1,38 @@
...
+struct slab_arena arena;
+struct slab_cache slabc;
+struct quota quota;
+
+void
+memcached_slab_arena_create()
+{
+	static __thread bool inited = false;
+	if (inited) return;
+	size_t quota_size = UINT_MAX;
```
Comment (Totktonada) [inline memcached/internal/alloc.c:38]: Why don't use `QUOTA_MAX`? We do that in tarantool for the runtime arena.

**Review by Totktonada — COMMENTED** [review]
Several small comments on the code. Aside of them the code look good.

I'm going to look into small versions compatibility over tarantool versions with symbols visible by default. After this I'll able to say, whether it completely resolves the problem or we need to work more on it.

File: memcached/internal/alloc.c [hunk 9]
```diff
@@ -1,2 +1,38 @@
...
+}
+
+void
+memcached_slab_cache_create()
+{
+	static __thread bool inited = false;
+	if (inited) return;
+	slab_cache_set_thread(&slabc);
+	slab_cache_create(&slabc, &arena);
+	say_info("allocate slab with size %u", arena.slab_size);
```
[the remark this answers is not in the document]
Comment (ligurio) [reply memcached/internal/alloc.c:54]: Updated:

```diff
--- a/memcached/internal/alloc.c
+++ b/memcached/internal/alloc.c
@@ -51,7 +51,7 @@ memcached_slab_cache_create()
        if (inited) return;
        slab_cache_set_thread(&slabc);
        slab_cache_create(&slabc, &arena);
-       say_info("allocate slab with size %u", arena.slab_size);
+       say_info("allocate slab cache with slab size %u", arena.slab_size);
        inited = 1;
 }
 
```

File: README.md [hunk 10]
```diff
@@ -79,6 +79,7 @@ END
 ## API
 
 * `local memcached = require('memcached')` - acquire a library handle
+* `local slab = memcached.slab()` - show information about slab arena and quota.
```
[the remark this answers is not in the document]
Comment (ligurio) [reply README.md:82]: > Also it is called slab() twice in the commit message.

First one as an example of output used in Tarantool, second one for demonstration of output added to memcached.

File: memcached/internal/alloc.c [hunk 11]
```diff
@@ -6,6 +6,30 @@ struct slab_arena arena;
...
+
+struct slab_arena_info slab_info;
+
+struct slab_arena_info *
+memcached_slab_arena_info()
+{
+	/*
+	* How much quota has been booked - reflects the total
+	* size of slabs in various slab caches.
+	*/
```
[the remark this answers is not in the document]
Comment (ligurio) [reply memcached/internal/alloc.c:23]: Added:

```diff
--- a/memcached/internal/alloc.c
+++ b/memcached/internal/alloc.c
@@ -14,13 +14,18 @@ struct slab_arena_info {
 
 struct slab_arena_info slab_info;
 
+/*
+ * Function produce an output with information of total quota size, used quota
+ * size and quota used ratio. Note that function relies on a fact that
+ * memcached uses a single slab cache for all allocations it made.
+ */
 struct slab_arena_info *
 memcached_slab_arena_info()
 {
        /*
-       * How much quota has been booked - reflects the total
-       * size of slabs in various slab caches.
-       */
+        * How much quota has been booked - reflects the total
+        * size of slabs in various slab caches.
+        */
        slab_info.quota_used = (uint64_t)quota_used(arena.quota);
 
        slab_info.quota_size = (uint64_t)quota_total(arena.quota);
```

File: memcached/internal/alloc.c [hunk 12]
```diff
@@ -1,74 +1,2 @@
 #include <tarantool/module.h>
 #include <small/slab_cache.h>
-
-void *
-box_persistent_malloc(size_t len, size_t *total)
```
[the remark this answers is not in the document]
Comment (ligurio) [reply memcached/internal/alloc.c:7]: It was intentional. I don't want to break a history for a file in a Git.

File: memcached/internal/alloc.c (hunk 8 above)
Comment (ligurio) [reply memcached/internal/alloc.c:38]: Fixed.

```diff
--- a/memcached/internal/alloc.c
+++ b/memcached/internal/alloc.c
@@ -11,7 +11,7 @@ memcached_slab_arena_create()
 {
        static __thread bool inited = false;
        if (inited) return;
-       size_t quota_size = UINT_MAX;
+       size_t quota_size = QUOTA_MAX;
        quota_init(&quota, quota_size);
        /* Parameters are the same as in src/lib/core/fiber.c */
        const size_t SLAB_SIZE = 4 * 1024 * 1024;

```

File: README.md [hunk 13]
```diff
@@ -79,6 +79,7 @@ END
 ## API
```
[the remark this answers is not in the document]
Comment (ligurio) [reply README.md:79]: Change was added in c66c437 "memcached: use own slab arena", updated commit messages.

File: README.md (hunk 10 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply README.md]: > It's a reason why new module function slab() was introduced.

Where I assume that `slab` is `memcached.slab`. It is not a function. `memcached.slab.info()` is the function.

> Output of slab() is similar to output from `box.slab.info()` <...>

Same here.

File: memcached/internal/alloc.c (hunk 12 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply memcached/internal/alloc.c:7]: We should either don't touch it neither in .c, nor .h file, or remove from both. Orphan declarations are confusing.

File: README.md (hunk 10 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply README.md]: Fixed.

File: memcached/internal/alloc.c (hunk 12 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply memcached/internal/alloc.c:7]: > Nit: We should remove them from alloc.h as well.

Fixed.

File: memcached/init.lua (hunk 7 above)
Comment (ligurio) [reply memcached/init.lua:412]: With patch below 64bit numbers are used.

```diff
diff --git a/memcached/init.lua b/memcached/init.lua
index ce42edb..2b8626b 100644
--- a/memcached/init.lua
+++ b/memcached/init.lua
@@ -409,7 +409,7 @@ local function memcached_slab_info()
     local slab_arena_info = memcached_internal.memcached_slab_arena_info()
     local slab_info = {}
     for _, v in pairs(slab_arena_info_table) do
-        slab_info[v] = tonumber(slab_arena_info[0][v])
+        slab_info[v] = tonumber64(slab_arena_info[0][v])
     end
     slab_info['quota_used_ratio'] = string.format('%0.2f%%', slab_info['quota_used_ratio'])
 
diff --git a/test/common/module_api.test.lua b/test/common/module_api.test.lua
index 5676680..3bb172a 100755
--- a/test/common/module_api.test.lua
+++ b/test/common/module_api.test.lua
@@ -57,11 +57,11 @@ test:is(#memcached.server, 0, 'memcached.server is empty')
 -- memcached.slab(): memcached module is initialized, no instances
 
 test:istable(memcached.slab, 'memcached.slab (no instances) returns a table')
-test:isfunction(memcached.slab.info, 'memcached.slab.info (no instances) returns a function')
+test:isfunction(memcached.slab.info, 'memcached.slab.info() (no instances) returns a function')
 local slab_info = memcached.slab.info()
-test:isnumber(slab_info.quota_size, 'memcached.slab.info().quota_size (no instances) returns a number')
+test:is(type(slab_info.quota_size), 'cdata', 'memcached.slab.info().quota_size (no instances) returns a cdata')
 test:is(slab_info.quota_size, 4398046510080, 'memcached.slab.info().quota_size (no instances) is correct')
-test:isnumber(slab_info.quota_used, 'memcached.slab.info().quota_used (no instances) returns a number')
+test:is(type(slab_info.quota_used), 'cdata', 'memcached.slab.info().quota_used (no instances) returns a cdata')
 test:is(slab_info.quota_used, 0, 'memcached.slab.info().quota_used (no instances) is correct')
 test:isstring(slab_info.quota_used_ratio, 'memcached.slab.info().quota_used_ratio (no instances) returns a string')
 
@@ -126,17 +126,17 @@ mc_1:start()
 mc_2:start()
 
 test:istable(memcached.slab, 'memcached.slab returns a table')
-test:isfunction(memcached.slab.info, 'memcached.slab.info returns a function')
+test:isfunction(memcached.slab.info, 'memcached.slab.info() returns a function')
 local slab_info = memcached.slab.info()
 test:istable(slab_info, 'memcached.slab.info() returns a table')
-test:isnumber(slab_info.quota_size, 'memcached.slab.info().quota_size returns a number')
+test:is(type(slab_info.quota_size), 'cdata', 'memcached.slab.info().quota_size returns a cdata')
 test:is(slab_info.quota_size, 4398046510080, 'memcached.slab.info().quota_size is correct')
-test:isnumber(slab_info.quota_used, 'memcached.slab.info().quota_used returns a number')
+test:is(type(slab_info.quota_used), 'cdata', 'memcached.slab.info().quota_used returns a cdata')
 test:is(slab_info.quota_used, 4194304, 'memcached.slab.info().quota_used is correct')
 test:isstring(slab_info.quota_used_ratio, 'memcached.slab.info().quota_used_ratio returns a string')
-local ratio = 100 * slab_info.quota_used / slab_info.quota_size
-local actual_ratio = string.match(slab_info.quota_used_ratio, '^(%d.%d+)%%')
-local eps_is_correct = abs(actual_ratio - ratio) < 1
+local expected_ratio = tonumber(100 * slab_info.quota_used / slab_info.quota_size)
+local actual_ratio = tonumber(slab_info.quota_used_ratio:match('^(%d.%d+)%%'))
+local eps_is_correct = abs(actual_ratio - expected_ratio) < 1
 test:is(eps_is_correct, true, 'memcached.slab.info().quota_used_ratio is correct')
 
 mc_1:stop()
```

NOTE: `tonumber64()` for big numbers returns a value with type `cdata`, not a `number`. `tap` module has a separate check for `cdata` - `taptest:iscdata()`, but it doesn't work for me. Check failed with unclear error.

`ffi.lua`:

```lua
local memcached = require('memcached')
local tap = require('tap')
local memcached = require('memcached')
local test = tap.test('memcached module api')
local size = memcached.slab.info().quota_size
assert(type(size) == 'cdata')
test:iscdata(size, 'memcached.slab.info().quota_size (no instances) returns a cdata')
```

```sh
sergeyb@pony:~/sources/MRG/memcached$ tarantool ffi.lua 
creating arena with 4398046510080 bytes...
allocate slab cache with slab size 4194304
TAP version 13
LuajitError: builtin/tap.lua:207: declaration specifier expected near 'memcached'
fatal error, exiting the event loop
```

Comment (Totktonada) [reply memcached/init.lua]: Regarding `iscdata()`: you passed the message in place of ctype ('uint64' in the case).

Comment (ligurio) [reply memcached/init.lua]: > Regarding iscdata(): you passed the message in place of ctype ('uint64' in the case).

Seems function prototype in [documentation](https://www.tarantool.io/en/doc/latest/reference/reference_lua/tap/#lua-function.taptest.iscdata) is incorrect: `taptest:iscdata(value, test-name)`.

**Comment by Totktonada** [comment]
> I'm going to look into small versions compatibility over tarantool versions with symbols visible by default. After this I'll able to say, whether it completely resolves the problem or we need to work more on it.

It is there: https://github.com/tarantool/memcached/issues/59#issuecomment-1081106140.

In short: we should freeze the libsmall revision in the module (just don't change it) and workaround the `ibuf_*` problem (I'll do in a separate PR).

File: memcached/init.lua (hunk 7 above)
Comment (Totktonada) [reply memcached/init.lua]: I got where I was wrong. I know that `tonumber64()` returns a value of type `'number'` for small numbers[^1], but I didn't know that `tonumber64()` returns cdata number for a small number passed as cdata number.

```lua
tarantool> type(tonumber64('0'))
---
- number
...

tarantool> type(tonumber64(0))
---
- number
...

tarantool> type(tonumber64(0ULL))
---
- cdata
...
```

That's why the test works: we just always return cdata numbers, at least on AMD64. `size_t` is 64 bit integer on AMD64 and the [FFI semantics](https://luajit.org/ext_ffi_semantics.html#convert_tolua) document states that LuaJIT converts those values to cdata numbers.

So `tonumber64()` is no-op. I would remove it. OTOH, it is harmless and I'll not insist.

Should we imitate `luaL_pushuint64()` behaviour, which is used in `box.slab.info()` and actually returns `'number'` for small values? I don't know a proper reason aside of 'most of tarantool functions behave this way'. So I'll not insist here too.

Since I have no strong agruments here, it is up to the author. I'll resolve the discussion.

[^1]: Here and below: less than or equal to 10^14-1.

**Review by Totktonada — APPROVED** [review]
LGTM.

**Comment by Totktonada** [comment]
@CuriousGeorgiy Reassigned, fixed the problem with accesses.

File: test/common/instance_api.test.lua [hunk 14]
```diff
@@ -0,0 +1,131 @@
+#!/usr/bin/env tarantool
+
+local socket = require('socket')
+local tap = require('tap')
+package.cpath = './?.so;' .. package.cpath
+local memcached = require('memcached')
+local test = tap.test('memcached instance api')
+
+local function is_port_open(port)
+    local sock, _ = socket.tcp_connect('127.0.0.1', port)
```
Comment (CuriousGeorgiy) [inline test/common/instance_api.test.lua:10]: Nit: why do you drop the error message here and don't display it? AFAIC, it could benefit test failure diagnostics.

File: test/common/instance_api.test.lua [hunk 15]
```diff
@@ -0,0 +1,131 @@
...
+test:is(is_port_open(mc_port), true, 'memcached instance is started')
+
+-- instance:stop()
+
+local self_instance = mc:stop()
+test:isnt(self_instance, nil, 'instance:stop() returns self object')
+test:is(is_port_open(mc_port), false, 'port is closed when memcached instance is stopped')
+local ok, err = pcall(mc.stop, mc)
+test:is(ok, false, 'instance:stop() of stopped instance is failed')
+test:like(err:gsub("^.+:%d+: ", ""), "Memcached instance 'memcached_xxx' is already stopped",
```
Comment (CuriousGeorgiy) [inline test/common/instance_api.test.lua:46]: Nit:
```suggestion
test:like(err:gsub("^.+:%d+: ", ""), "Memcached instance '%s' is already stopped":format(mc_name),
```

File: test/common/instance_api.test.lua [hunk 16]
```diff
@@ -0,0 +1,131 @@
...
+    'instance:stop() of stopped instance shows a correct error message')
+
+-- instance:start()
+
+local self_instance = mc:start()
+test:isnt(self_instance, nil, 'instance:start() returns self object')
+test:is(is_port_open(mc_port), true, 'instance:start() opens a port')
+local ok, err = pcall(mc.start, mc)
+test:is(ok, false, 'instance:start() of started instance is failed')
+test:like(err:gsub("^.+:%d+: ", ""), "Memcached instance 'memcached_xxx' is already started",
```
Comment (CuriousGeorgiy) [inline test/common/instance_api.test.lua:56]: Nit:
```suggestion
test:like(err:gsub("^.+:%d+: ", ""), "Memcached instance '%s' is already stopped":format(mc_name),
```

File: test/common/instance_api.test.lua [hunk 17]
```diff
@@ -0,0 +1,131 @@
...
+local mc = memcached.create(mc_name, tostring(mc_port), {
+    space_name = mc_space_name
+})
+test:isnt(mc, nil, 'memcached instance object is not nil')
+test:is(is_port_open(mc_port), true, 'memcached instance is started')
+
+-- instance:stop()
+
+local self_instance = mc:stop()
+test:isnt(self_instance, nil, 'instance:stop() returns self object')
```
Comment (CuriousGeorgiy) [inline test/common/instance_api.test.lua:42]: I didn't quite understand from the README: isn't `self_instance == mc`?

File: test/common/instance_api.test.lua [hunk 18]
```diff
@@ -0,0 +1,131 @@
...
+local self_instance = mc:cfg({
+    expire_full_scan_time = updated_expire_full_scan_time,
+    expire_items_per_iter = updated_expire_items_per_iter,
+    expire_enabled = updated_expire_enabled,
+    protocol = updated_protocol,
+    name = updated_name,
+    verbosity = updated_verbosity,
+    sasl = updated_sasl,
+})
+test:isnt(self_instance, nil, 'instance:cfg() returns a self object')
```
Comment (CuriousGeorgiy) [inline test/common/instance_api.test.lua:113]: I didn't quite understand from the README: isn't `self_instance == mc`?

File: test/common/instance_api.test.lua [hunk 19]
```diff
@@ -0,0 +1,131 @@
...
+    'instance:cfg() updated expire_enabled correctly')
+test:is(mc.opts.protocol, updated_protocol, 'instance:cfg() updated protocol correctly')
+test:is(mc.opts.verbosity, updated_verbosity, 'instance:cfg() updated verbosity correctly')
+test:is(mc.opts.sasl, updated_sasl, 'instance:cfg() updated sasl correctly')
+
+-- instance:grant()
+
+box.schema.user.create('Vera')
+local self_instance = mc:grant('Vera')
+test:isnt(self_instance, nil, 'instance:grant() returns self object')
```
Comment (CuriousGeorgiy) [inline test/common/instance_api.test.lua:129]: I didn't quite understand from the README: isn't `self_instance == mc`?

File: test/common/module_api.test.lua [hunk 20]
```diff
@@ -0,0 +1,87 @@
+#!/usr/bin/env tarantool
+
+local socket = require('socket')
+local tap = require('tap')
+package.cpath = './?.so;' .. package.cpath
+local memcached = require('memcached')
+local test = tap.test('memcached module api')
+
+local function is_port_open(port)
+    local sock, _ = socket.tcp_connect('127.0.0.1', port)
```
Comment (CuriousGeorgiy) [inline test/common/module_api.test.lua]: Ditto.

File: test/common/module_api.test.lua [hunk 21]
```diff
@@ -0,0 +1,87 @@
...
+    if not sock then
+        return false
+    end
+    return sock:sysconnect(0, port) and true or false
```
Comment (CuriousGeorgiy) [inline test/common/module_api.test.lua]: Ditto.

File: test/common/module_api.test.lua [hunk 22]
```diff
@@ -0,0 +1,87 @@
...
+-- memcached.server: module is initialized, no instances
+
+test:istable(memcached.server, 'type of memcached.server is a table')
+test:is(#memcached.server, 0, 'memcached.server is empty')
+
+-- memcached.create(): instance 1
+
+local mc_1_port = 11211
+local mc_1_name = 'memcached_1_xxx'
+local mc_1_space_name = 'memcached_xxx_1_space'
```
Comment (CuriousGeorgiy) [inline test/common/module_api.test.lua:75]: Nit: 
```suggestion
local mc_1_space_name = 'memcached_1_xxx_space'
```

File: test/common/module_api.test.lua [hunk 23]
```diff
@@ -0,0 +1,87 @@
...
+    space_name = mc_2_space_name
+})
+test:isnt(mc_2, nil, '2nd memcached instance object is not nil')
+test:is(is_port_open(mc_2_port), true, '2nd memcached instance is started')
+mc_2:stop()
+
+-- memcached.server with created and started instances
+
+mc_1:start()
+mc_2:start()
```
Comment (CuriousGeorgiy) [inline test/common/module_api.test.lua:100]: Nit: aren't they already started?

File: test/common/module_api.test.lua [hunk 24]
```diff
@@ -0,0 +1,87 @@
...
+    }
+    box.schema.user.grant('guest', 'read,write,execute', 'universe')
+end
+
+test:plan(15)
+
+-- memcached.server: module is initialized, no instances
+
+test:istable(memcached.server, 'type of memcached.server is a table')
+test:is(#memcached.server, 0, 'memcached.server is empty')
```
Comment (CuriousGeorgiy) [inline test/common/module_api.test.lua:56]: I don't get the point of testing this.

File: test/common/module_api.test.lua [hunk 25]
```diff
@@ -0,0 +1,87 @@
...
+test:is(is_port_open(mc_2_port), true, '2nd memcached instance is started')
+mc_2:stop()
+
+-- memcached.server with created and started instances
+
+mc_1:start()
+mc_2:start()
+
+test:istable(memcached.server, 'type of memcached.server is a table')
+test:is(#memcached.server, 0, 'memcached.server is empty')
```
Comment (CuriousGeorgiy) [inline test/common/module_api.test.lua:103]: Nit: what is the point of testing this twice?

File: test/common/instance_api.test.lua [hunk 26]
```diff
@@ -0,0 +1,131 @@
...
+package.cpath = './?.so;' .. package.cpath
+local memcached = require('memcached')
+local test = tap.test('memcached instance api')
+
+local function is_port_open(port)
+    local sock, _ = socket.tcp_connect('127.0.0.1', port)
+    if sock == nil then
+        return false
+    end
+    return sock:sysconnect(0, port) and true or false
```
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua:14]: connect to remote host, see https://www.tarantool.io/en/doc/latest/reference/reference_lua/socket/#socket-sysconnect

File: test/common/instance_api.test.lua [hunk 27]
```diff
@@ -0,0 +1,131 @@
...
+test:is(instance_info.incr_hits, 0, 'default value of incr_hits is correct')
+test:is(instance_info.cmd_delete, 0, 'default value of cmd_delete is correct')
+test:is(instance_info.cas_misses, 0, 'default value of cas_misses is correct')
+test:is(instance_info.bytes_read, 0, 'default value of bytes_read is correct')
+test:is(instance_info.cas_badval, 0, 'default value of cas_badval is correct')
+test:is(instance_info.delete_hits, 0, 'default value of delete_hits is correct')
+test:is(instance_info.cmd_get, 0, 'default value of cmd_get is correct')
+test:is(instance_info.cas_hits, 0, 'default value of cas_hits is correct')
+test:is(instance_info.cmd_set, 0, 'default value of cmd_set is correct')
+test:is(instance_info.get_misses, 0, 'default value of get_misses is correct')
```
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua:92]: Seems it is not documented anywhere.

File: test/common/instance_api.test.lua [hunk 28]
```diff
@@ -0,0 +1,131 @@
...
+test:is(is_port_open(mc_port), false, 'port is closed when memcached instance is stopped')
+local ok, err = pcall(mc.stop, mc)
+test:is(ok, false, 'instance:stop() of stopped instance is failed')
+test:like(err:gsub("^.+:%d+: ", ""), "Memcached instance 'memcached_xxx' is already stopped",
+    'instance:stop() of stopped instance shows a correct error message')
+
+-- instance:start()
+
+local self_instance = mc:start()
+test:isnt(self_instance, nil, 'instance:start() returns self object')
```
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua:52]: `mc` is an object for memcached module, `mc:start()` returns an object for a memcached instance.

File: test/common/instance_api.test.lua [hunk 29]
```diff
@@ -0,0 +1,131 @@
...
+    box.schema.user.grant('guest', 'read,write,execute', 'universe')
+end
+
+test:plan(50)
+
+-- memcached.create()
+
+local mc_port = 11211
+local mc_name = 'memcached_xxx'
+local mc_space_name = 'memcached_aaa_space'
```
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua:31]: Why the name of test instance is important?

File: test/common/module_api.test.lua [hunk 30]
```diff
@@ -6,12 +6,36 @@ package.cpath = './?.so;' .. package.cpath
 local memcached = require('memcached')
 local test = tap.test('memcached module api')
 
-local function is_port_open(port)
-    local sock, _ = socket.tcp_connect('127.0.0.1', port)
-    if not sock then
+-- 1. Open connection to memcached instance.
```
Comment (CuriousGeorgiy) [inline test/common/module_api.test.lua:11]: Nit: perhaps this should be squashed with efe54476?

File: memcached/internal/alloc.c [hunk 31]
```diff
@@ -1,2 +1,38 @@
...
+struct quota quota;
+
+void
+memcached_slab_arena_create()
+{
+	static __thread bool inited = false;
+	if (inited) return;
+	size_t quota_size = QUOTA_MAX;
+	quota_init(&quota, quota_size);
+	/* Parameters are the same as in src/lib/core/fiber.c */
```
Comment (CuriousGeorgiy) [inline memcached/internal/alloc.c:45]:
```suggestion
/* Parameters are the same as in src/lib/core/memory.c:memory_init */
```

File: memcached/init.lua [hunk 32]
```diff
@@ -82,6 +82,10 @@ memcached_get_stat (struct memcached_service *);
 struct memcached_service *
 memcached_create(const char *, uint32_t);
 
+void memcached_slab_arena_create();
```
Comment (CuriousGeorgiy) [inline memcached/init.lua:91]: AFAIC, you didn't cover module deinitialization: why shouldn't we care about module unloading from Lua? It seems there are [ways](https://www.freelists.org/post/luajit/BUG-Assertion-failures-when-unloading-and-reloading-the-ffi-package,1) to do this in runtime, so we should care about this.

Perhaps adding a routine with `__attribute__((__destructor__))` would suffice?

**Review by CuriousGeorgiy — CHANGES_REQUESTED** [review]
> I would like to see allocator (de)initialization code in memcached/internal/alloc.c. I guess three new functions: initialization, deinitialization, get slab cache pointer.

Me too. At least, I would like to see a clarification from Lango team that this is not required or possible: the potential memory leak that could be caused by module unload boggles me.

File: test/common/instance_api.test.lua (hunk 15 above)
Comment (ligurio) [reply test/common/instance_api.test.lua:46]: Fixed.

```diff
--- a/test/common/instance_api.test.lua
+++ b/test/common/instance_api.test.lua
@@ -43,7 +43,7 @@ test:isnt(self_instance, nil, 'instance:stop() returns self object')
 test:is(is_port_open(mc_port), false, 'port is closed when memcached instance is stopped')
 local ok, err = pcall(mc.stop, mc)
 test:is(ok, false, 'instance:stop() of stopped instance is failed')
-test:like(err:gsub("^.+:%d+: ", ""), "Memcached instance 'memcached_xxx' is already stopped",
+test:like(err:gsub("^.+:%d+: ", ""), ("Memcached instance '%s' is already stopped"):format(mc_name),
     'instance:stop() of stopped instance shows a correct error message')
 
 -- instance:start()
```

File: test/common/instance_api.test.lua (hunk 16 above)
Comment (ligurio) [reply test/common/instance_api.test.lua:56]: Fixed.

```diff
@@ -53,7 +53,7 @@ test:isnt(self_instance, nil, 'instance:start() returns self object')
 test:is(is_port_open(mc_port), true, 'instance:start() opens a port')
 local ok, err = pcall(mc.start, mc)
 test:is(ok, false, 'instance:start() of started instance is failed')
-test:like(err:gsub("^.+:%d+: ", ""), "Memcached instance 'memcached_xxx' is already started",
+test:like(err:gsub("^.+:%d+: ", ""), ("Memcached instance 'memcached_xxx' is already started"):format(mc_name),
     'instance:start() of started instance shows a correct error message')
 
 -- instance:info()
```

File: test/common/instance_api.test.lua (hunk 17 above)
Comment (ligurio) [reply test/common/instance_api.test.lua:42]: Yes, according to documented behavior in the README `mc` is the same as `self_instance`. assert checks that behavior.

File: test/common/instance_api.test.lua (hunk 18 above)
Comment (ligurio) [reply test/common/instance_api.test.lua:113]: Yes, according to documented behavior in the README mc is the same as self_instance. assert checks that behavior.
See also an implementation of stop() method: https://github.com/tarantool/memcached/blob/master/memcached/init.lua#L310-L320

File: test/common/instance_api.test.lua (hunk 19 above)
Comment (ligurio) [reply test/common/instance_api.test.lua:129]: Yes, according to documented behavior in the README mc is the same as self_instance. assert checks that behavior.
See also an implementation of stop() method: https://github.com/tarantool/memcached/blob/master/memcached/init.lua#L310-L320

File: test/common/module_api.test.lua [hunk 33]
```diff
@@ -0,0 +1,87 @@
...
+
+local socket = require('socket')
+local tap = require('tap')
+package.cpath = './?.so;' .. package.cpath
+local memcached = require('memcached')
+local test = tap.test('memcached module api')
+
+local function is_port_open(port)
+    local sock, _ = socket.tcp_connect('127.0.0.1', port)
+    if not sock then
```
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/module_api.test.lua]: Fixed.

```diff
--- a/test/common/module_api.test.lua
+++ b/test/common/module_api.test.lua
@@ -8,7 +8,7 @@ local test = tap.test('memcached module api')
 
 local function is_port_open(port)
     local sock, _ = socket.tcp_connect('127.0.0.1', port)
-    if not sock then
+    if sock == nil then
         return false
     end
     return sock:sysconnect(0, port) and true or false
```

File: test/common/instance_api.test.lua (hunk 29 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua:31]: Fixed.

```diff
--- a/test/common/instance_api.test.lua
+++ b/test/common/instance_api.test.lua
@@ -28,7 +28,7 @@ test:plan(50)
 
 local mc_port = 11211
 local mc_name = 'memcached_xxx'
-local mc_space_name = 'memcached_aaa_space'
+local mc_space_name = 'memcached_xxx_space'
 
 local mc = memcached.create(mc_name, tostring(mc_port), {
     space_name = mc_space_name
```

File: test/common/module_api.test.lua (hunk 24 above)
Comment (ligurio) [reply test/common/module_api.test.lua:56]: `memcached.server` is empty when no started instances.

File: memcached/internal/alloc.c (hunk 31 above)
Comment (ligurio) [reply memcached/internal/alloc.c:45]: Fixed.

```diff
--- a/memcached/internal/alloc.c
+++ b/memcached/internal/alloc.c
@@ -42,7 +42,7 @@ memcached_slab_arena_create()
        if (inited) return;
        size_t quota_size = QUOTA_MAX;
        quota_init(&quota, quota_size);
-       /* Parameters are the same as in src/lib/core/fiber.c */
+       /* Parameters are the same as in src/lib/core/memory.c:memory_init() */
        const size_t SLAB_SIZE = 4 * 1024 * 1024;
        slab_arena_create(&arena, &quota, 0, SLAB_SIZE, SLAB_ARENA_PRIVATE);
        say_info("creating arena with %zu bytes...", quota_size);
```

File: memcached/internal/alloc.c [hunk 34]
```diff
@@ -1,2 +1,38 @@
 #include <tarantool/module.h>
 #include <small/slab_cache.h>
+#include <small/quota.h>
+
+struct slab_arena arena;
+struct slab_cache slabc;
+struct quota quota;
```
[the remark this answers is not in the document]
Comment (ligurio) [reply memcached/internal/alloc.c:7]: Good idea, thanks!

```diff
diff --git a/memcached/internal/alloc.c b/memcached/internal/alloc.c                                                               
index 2b25bca..0e78ecc 100644                                                                                                      
--- a/memcached/internal/alloc.c                                                                                                   
+++ b/memcached/internal/alloc.c                                                                                                   
@@ -2,9 +2,9 @@                                                                                                                    
 #include <small/slab_cache.h>
 #include <small/quota.h>

-struct slab_arena arena;                                                                                                          
-struct slab_cache slabc;                                                                                                          
-struct quota quota;                                                                                                               
+static struct slab_arena arena;                                                                                                   
+static struct slab_cache slabc;                                                                                                   
+static struct quota quota;                                                                                                        

 void
 memcached_slab_arena_create()
```

File: test/common/module_api.test.lua (hunk 22 above)
Comment (CuriousGeorgiy) [reply test/common/module_api.test.lua:75]: But `mc_1_space_name` is `memcached` + `xxx` + number of instance + `space`?

File: test/common/module_api.test.lua (hunk 30 above)
Comment (ligurio) [reply test/common/module_api.test.lua:11]: No. First version is a simple check port for openness. After introducing own small arena I need a simple memcached client to trigger allocations in memcached fiber.

File: test/common/module_api.test.lua (hunk 23 above)
Comment (ligurio) [reply test/common/module_api.test.lua:100]: No. It is stopped above.

File: test/common/instance_api.test.lua (hunk 26 above)
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply test/common/instance_api.test.lua:14]: But doesn't `socket.tcp_connect('127.0.0.1', port)` do the same?

File: test/common/instance_api.test.lua (hunk 17 above)
Comment (CuriousGeorgiy) [reply test/common/instance_api.test.lua:42]: Wouldn't this kind of test be better?
```suggestion
test:is(self_instance, mc, 'instance:stop() returns self object')
```

File: test/common/instance_api.test.lua (hunk 28 above)
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply test/common/instance_api.test.lua:52]: Wouldn't this kind of test be better?
```suggestion
test:is(self_instance, mc, 'instance:stop() returns self object')
```

File: test/common/instance_api.test.lua (hunk 18 above)
Comment (CuriousGeorgiy) [reply test/common/instance_api.test.lua:113]: Wouldn't this kind of test be better?
```suggestion
test:is(self_instance, mc, 'instance:stop() returns self object')
```

File: test/common/instance_api.test.lua (hunk 19 above)
Comment (CuriousGeorgiy) [reply test/common/instance_api.test.lua:129]: Wouldn't this kind of test be better?
```suggestion
test:is(self_instance, mc, 'instance:stop() returns self object')
```

File: test/common/module_api.test.lua (hunk 23 above)
Comment (CuriousGeorgiy) [reply test/common/module_api.test.lua:100]: Beg your pardon, I didn't notice that.

File: test/common/module_api.test.lua (hunk 24 above)
Comment (CuriousGeorgiy) [reply test/common/module_api.test.lua:56]: But then why is it also empty on lines 63-64 (you missed the comment there apparently)?

AFAIC, you cannot even use the length operator on this table, as it is not an array:
https://github.com/tarantool/memcached/blob/5aaac8383ee9b04ecaac701c289ac3712ba48f8c/memcached/init.lua#L379-L382

**Review by CuriousGeorgiy — APPROVED** [review]

**Comment by CuriousGeorgiy** [comment]
@Totktonada FYI, for some reason I cannot resolve conversations in this PR and my status near `Reviewers` section is displayed grey.

**Comment by Totktonada** [comment]
> @Totktonada FYI, for some reason I cannot resolve conversations in this PR and my status near `Reviewers` section is displayed grey.

Should be resolved now. I re-requested the review to test it.

**Review by CuriousGeorgiy — APPROVED** [review]

**Comment by CuriousGeorgiy** [comment]
@Totktonada It works now, thanks!

File: test/common/instance_api.test.lua (hunk 28 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua:52]: Fixed.

```diff
diff --git a/test/common/instance_api.test.lua b/test/common/instance_api.test.lua
index cfdfd04..1faa09b 100755
--- a/test/common/instance_api.test.lua
+++ b/test/common/instance_api.test.lua
@@ -39,7 +39,7 @@ test:is(is_port_open(mc_port), true, 'memcached instance is started')
 -- instance:stop()
 
 local self_instance = mc:stop()
-test:isnt(self_instance, nil, 'instance:stop() returns self object')
+test:is(self_instance, mc, 'instance:stop() returns self object')
 test:is(is_port_open(mc_port), false, 'port is closed when memcached instance is stopped')
 local ok, err = pcall(mc.stop, mc)
 test:is(ok, false, 'instance:stop() of stopped instance is failed')
@@ -49,7 +49,7 @@ test:like(err:gsub("^.+:%d+: ", ""), ("Memcached instance '%s' is already stoppe
 -- instance:start()
 
 local self_instance = mc:start()
-test:isnt(self_instance, nil, 'instance:start() returns self object')
+test:is(self_instance, mc, 'instance:start() returns self object')
 test:is(is_port_open(mc_port), true, 'instance:start() opens a port')
 local ok, err = pcall(mc.start, mc)
 test:is(ok, false, 'instance:start() of started instance is failed')
@@ -110,7 +110,7 @@ local self_instance = mc:cfg({
     verbosity = updated_verbosity,
     sasl = updated_sasl,
 })
-test:isnt(self_instance, nil, 'instance:cfg() returns a self object')
+test:is(self_instance, mc, 'instance:cfg() returns a self object')
 test:is(is_port_open(mc_port), true, 'instance:cfg() keeps port opened')
 test:is(mc.opts.expire_full_scan_time, updated_expire_full_scan_time,
     'instance:cfg() updated expire_full_scan_time correctly')
@@ -126,6 +126,6 @@ test:is(mc.opts.sasl, updated_sasl, 'instance:cfg() updated sasl correctly')
 
 box.schema.user.create('Vera')
 local self_instance = mc:grant('Vera')
-test:isnt(self_instance, nil, 'instance:grant() returns self object')
+test:is(self_instance, mc, 'instance:grant() returns self object')
 
 os.exit(test:check() and 0 or 1)
```

File: test/common/instance_api.test.lua (hunk 19 above)
Comment (ligurio) [reply test/common/instance_api.test.lua:129]: Fixed.

File: test/common/instance_api.test.lua (hunk 18 above)
Comment (ligurio) [reply test/common/instance_api.test.lua:113]: Fixed.

File: test/common/instance_api.test.lua (hunk 17 above)
Comment (ligurio) [reply test/common/instance_api.test.lua:42]: Fixed,

File: test/common/instance_api.test.lua (hunk 26 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply test/common/instance_api.test.lua]: Fixed.

```diff
--- a/test/common/instance_api.test.lua
+++ b/test/common/instance_api.test.lua
@@ -11,7 +11,7 @@ local function is_port_open(port)
     if sock == nil then
         return false
     end
-    return sock:sysconnect(0, port) and true or false
+    return true
 end
 
 if type(box.cfg) == 'function' then
```

File: test/common/module_api.test.lua (hunk 21 above)
Comment (ligurio) [reply test/common/module_api.test.lua]: Fixed.

```diff
--- a/test/common/module_api.test.lua
+++ b/test/common/module_api.test.lua
@@ -11,7 +11,7 @@ local function is_port_open(port)
     if sock == nil then
         return false
     end
-    return sock:sysconnect(0, port) and true or false
+    return true
 end
 
 if type(box.cfg) == 'function' then
```
